import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    home: 'Home',
    menu: 'Menu',
    trackOrder: 'Track Order',
    profile: 'Profile',
    cart: 'Cart',
    signIn: 'Sign In',
    orders: 'Orders',
    heroTag: '🚀 Fast Delivery · Fresh Food',
    heroTitle: 'Delicious Food, Delivered Fast 🍕',
    heroSub: 'Order from the best restaurants near you. Fresh, hot & on time — every time.',
    orderNow: 'Order Now →',
    trackMyOrder: 'Track My Order',
    browseCategories: 'Browse Categories',
    craving: 'What are you craving today?',
    mostPopular: 'Most Popular',
    viewFullMenu: 'View Full Menu →',
    ourMenu: 'Our Menu',
    freshIngredients: 'Fresh ingredients, bold flavours — made just for you',
    searchPlaceholder: 'Search dishes...',
    itemsFound: '{count} items found',
    noItemsFound: 'No items found. Try a different search or category.',
    yourCart: '🛒 Your Cart',
    cartEmptyTitle: 'Your cart is empty',
    cartEmptyMessage: 'Add some delicious items to get started!',
    browseMenu: 'Browse Menu →',
    orderSummary: 'Order Summary',
    deliveryFee: 'Delivery fee',
    promoCode: 'Promo code',
    apply: 'Apply',
    tryPromo: 'Try: FLAVOR10 or RUSH20',
    total: 'Total',
    proceedCheckout: 'Proceed to Checkout →',
    promoAlready: 'Promo already applied!',
    promoInvalid: '❌ Invalid promo code. Try FLAVOR10 or RUSH20',
    checkout: 'Checkout',
    deliveryDetails: '📍 Delivery Details',
    firstName: 'First Name *',
    lastName: 'Last Name *',
    phoneNumber: 'Phone Number *',
    deliveryAddress: 'Delivery Address *',
    city: 'City *',
    postalCode: 'Postal Code',
    paymentMethod: '💳 Payment Method',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cashOnDelivery: 'Pay with cash when your order arrives. Have exact change ready!',
    onlinePay: 'You will receive a payment link via SMS after placing the order.',
    placeOrder: 'Place Order 🎉',
    secureNote: '🔒 100% Secure & Encrypted Payment',
    fillRequired: '⚠️ Please fill all required fields',
    trackYourOrder: 'Track Your Order',
    orderId: 'Order ID',
    status: 'Your order is on the way! 🚴',
    eta: '⏱ Estimated delivery: 25 minutes',
    orderConfirmed: 'Order Confirmed',
    preparing: 'Preparing',
    outForDelivery: 'Out for Delivery',
    delivered: 'Delivered',
    driver: 'Nuwan Jayasinghe',
    driverSub: 'Your delivery partner · ⭐ 4.9 rating',
    call: '📞 Call',
    chat: '💬 Chat',
    liveMap: 'Live Map Tracking',
    integrateMap: 'Integrate Google Maps API here',
    personalInfo: 'Personal Info',
    savedAddresses: 'Saved Addresses',
    addNewAddress: '+ Add New Address',
    homeLabel: 'Home',
    office: 'Office',
    edit: 'Edit',
    orderHistory: 'Order History',
    orderAgain: '+ Order Again',
    welcomeBack: 'Welcome back! 👋',
    createAccount: 'Create your account 🍕',
    login: 'Login',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    createAccountBtn: 'Create Account 🎉',
    haveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    switchToLogin: 'Login',
    switchToRegister: 'Register',
    demoHint: '💡 Demo: enter any email/password',
    invalidCredentials: '⚠️ Enter email and password',
    invalidConfirm: '❌ Passwords must match',
    accountCreated: '🎉 Account created successfully!',
    welcomeBackToast: '👋 Welcome back!',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    downloadApp: 'Download App',
    accept: 'We Accept',
    subscribe: 'Subscribe →',
  },
  si: {
    home: 'මුල් පිටුව',
    menu: 'මෙනු',
    trackOrder: 'ඇණවුම පරීක්ෂා කරන්න',
    profile: 'ප්‍රොෆයිලය',
    cart: 'කාට්',
    signIn: 'පුරන්න',
    orders: 'ඇණවුම්',
    heroTag: '🚀 වේගවත් බෙදාහැරීම · තාජා ආහාර',
    heroTitle: 'රසවත් ආහාරය, ඉක්මනින් බෙදාහැරේ 🍕',
    heroSub: 'ඔබට ළඟම තිබෙන හොඳම ආපනශාලාවෙන් ඇණවුම් කරන්න. පිරිසිදු, රසවත් සහ කාලයට ගැළපෙන.',
    orderNow: 'දැන් ඇණවුම් කරන්න →',
    trackMyOrder: 'මගේ ඇණවුම පරීක්ෂා කරන්න',
    browseCategories: 'වර්ග අනුව බලන්න',
    craving: 'ඔබට අද කැමති දේ කුමක්ද?',
    mostPopular: 'ප්‍රචලිතම',
    viewFullMenu: 'සම්පූර්ණ මෙනුව බලන්න →',
    ourMenu: 'අපගේ මෙනු',
    freshIngredients: 'තහඩු ඇති අවශ්‍ය ද්‍රව්‍ය, සහ රසමය ටිකක් — ඔබ වෙනුවෙන්.',
    searchPlaceholder: 'වෙළඳ නාමය සෙවන්න...',
    itemsFound: '{count} වස්තු හමුවි',
    noItemsFound: 'වස්තු හමුවූ නැත. වෙනත් සෙවුමක් හෝ වර්ගයක් උත්සහ කරන්න.',
    yourCart: '🛒 ඔබේ කාට්',
    cartEmptyTitle: 'ඔබේ කාට් හිස්යි',
    cartEmptyMessage: 'ආහාරබර වස්තු එක් කරන්න, ආරම්භ කරන්න!',
    browseMenu: 'මෙනුව බලා ගන්න →',
    orderSummary: 'ඇණවුම් සාරාංශය',
    deliveryFee: 'බෙදාහැරීමේ ගාස්තුව',
    promoCode: 'ප්‍රවර්ධන කේතය',
    apply: 'අදාළ කරන්න',
    tryPromo: 'උත්සහ කරන්න: FLAVOR10 හෝ RUSH20',
    total: 'එකතුව',
    proceedCheckout: 'කඩදාසි එකට →',
    promoAlready: 'ප්‍රවර්ධන කේතය දැනටමත් භාවිතා කර ඇත!',
    promoInvalid: '❌ වැරදි කේතය. FLAVOR10 හෝ RUSH20 උත්සහ කරන්න',
    checkout: 'ගෙවීම්',
    deliveryDetails: '📍 බෙදාහැරීමේ විස්තර',
    firstName: 'මුල් නම *',
    lastName: 'අවසන් නම *',
    phoneNumber: 'දුරකථන අංකය *',
    deliveryAddress: 'බෙදාහැරීමේ ලිපිනය *',
    city: 'නගරය *',
    postalCode: 'තැපැල් කේතය',
    paymentMethod: '💳 ගෙවීම් ක්‍රමය',
    cardNumber: 'කාඩ් අංකය',
    expiryDate: 'වළඳ දිනය',
    cvv: 'CVV',
    cashOnDelivery: 'ඔබේ ඇණවුම පැමිණියේ පසුව මුදල් ගෙවන්න. හරියට මුදල් සූදානම් කරන්න!',
    onlinePay: 'ඇණවුම තබාගත් පසු SMS මඟින් ගෙවීම් සබැඳියක් ලැබේ.',
    placeOrder: 'ඇණවුම තබන්න 🎉',
    secureNote: '🔒 100% ආරක්ෂිත සහ ගුප්ත ගෙවීම',
    fillRequired: '⚠️ අවශ්‍ය ක්ෂේත්‍ර සියල්ල පිරවන්න',
    trackYourOrder: 'ඔබේ ඇණවුම පරීක්ෂා කරන්න',
    orderId: 'ඇණවුම් අංකය',
    status: 'ඔබගේ ඇණවුම මාර්ගයේයි! 🚴',
    eta: '⏱ පැය 25 ක් ඇතුළත් බෙදාහැරීම',
    orderConfirmed: 'ඇණවුම තහවුරු කරන ලදී',
    preparing: 'සැකසෙමින්',
    outForDelivery: 'බෙදාහැරීමට පිටව ඇත',
    delivered: 'බෙදාහැරුණා',
    driver: 'නුවන් ජයසිංහ',
    driverSub: 'ඔබේ බෙදාහැරීම් හවුල්කරු · ⭐ 4.9 ශ්‍රේණිය',
    call: '📞 ඇමතුම',
    chat: '💬 කතාබස්',
    liveMap: 'සජීවී සිතියම් පීණු',
    integrateMap: 'මෙහි Google Maps API එකතු කරන්න',
    personalInfo: 'පුද්ගලික තොරතුරු',
    savedAddresses: 'සුරක්ෂිත ලිපින',
    addNewAddress: '+ නව ලිපිනයක් එකතු කරන්න',
    homeLabel: 'නිවස',
    office: 'කාර්යාලය',
    edit: 'සංස්කරණය',
    orderHistory: 'ඇණවුම් ඉතිහාසය',
    orderAgain: '+ නැවත ඇණවුම් කරන්න',
    welcomeBack: 'ආයුබෝවන් නැවත! 👋',
    createAccount: 'ඔබගේ ගිණුම නිර්මාණය කරන්න 🍕',
    login: 'පුරන්න',
    register: 'ලියාපදිංචි වන්න',
    email: 'ඊමේල් ලිපිනය',
    password: 'මුරපදය',
    forgotPassword: 'මුරපදය අමතක වුණා?',
    createAccountBtn: 'ගිණුම තනන්න 🎉',
    haveAccount: 'දැනට ගිණුමක් තියෙනවාද?',
    dontHaveAccount: 'ගිණුමක් නැද්ද?',
    switchToLogin: 'පුරන්න',
    switchToRegister: 'ලියාපදිංචි වන්න',
    demoHint: '💡 උදාහරණය: ඕනෑම email/password එකක් යොදන්න',
    invalidCredentials: '⚠️ ඉමේල් සහ මුරපදය ඇතුළත් කරන්න',
    invalidConfirm: '❌ මුරපද නොගැලපේ',
    accountCreated: '🎉 ගිණුම සාර්ථකව නිර්මාණය විය!',
    welcomeBackToast: '👋 ආයුබෝවන් නැවත!',
    quickLinks: 'පෙරළන සබැඳි',
    contactUs: 'අප අමතන්න',
    downloadApp: 'යෙදුම බාගන්න',
    accept: 'අපි පිළිගෙනයි',
    subscribe: 'දායක වන්න →',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = useCallback((key, fallback) => {
    const value = translations[language]?.[key];
    return value ?? fallback ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};
